#!/bin/sh

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
# echo $SCRIPTPATH

BASE=$SCRIPTPATH/..
PWD=`pwd`

# Association
echo 'Association rule analyzing ...'
cd $BASE/modules/association
ant -Dcmd="$*"
cd $PWD
echo 'Association rule analyzing result has been stored in files.'
