#!/bin/sh

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
# echo $SCRIPTPATH

BASE=$SCRIPTPATH/..
PWD=`pwd`

# Check Mongo Section|block|table header
echo 'Document parsed label checking ...'
cd $BASE/modules/checklabel
ant run -Dcmd="$*"
cd $PWD
echo 'Check result has been strored in file.'
