#!/bin/sh

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
# echo $SCRIPTPATH

BASE=$SCRIPTPATH/..
PWD=`pwd`

# cluster iteration
echo 'Run clustering ...'
cd $BASE/modules/classify/
python cluster.py $*
#  ant cluster -Diter=$1
cd $PWD
echo $1' clustering done.'
exit 1
