#!/bin/sh

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
# echo $SCRIPTPATH

BASE=$SCRIPTPATH/..
PWD=`pwd`

# classify iteration
echo 'Run classifying ...'
cd $BASE/modules/classify
python classify.py $*
#  ant classify -Diter=$1
cd $PWD
echo 'Classifying done.'

exit 1
