#!/bin/sh

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
# echo $SCRIPTPATH

BASE=$SCRIPTPATH/..
PWD=`pwd`

usage()
{
  echo 'Usage: ./clsdata -l <type> [-o <output>][configs for run file]'
  echo 'type: document, section, table'
  echo 'output: data or log output path name. The data output path will be "data/youroutputname". The log output path will be "log/youroutputname"'
  echo 'configs will be pass to run command'
  exit 1
}

if [ $# -lt '2' ]
  then
    usage
fi

# cluster-classify iteration preparation
echo 'Preparing ducoment and feature data for iteration ...'

TYPE=$2

case $TYPE in
    'document') 
        OUTPUT='DocClassify'
        EXEC=start.sh
        ;;
    'section')
        OUTPUT='SectionClassify'
        EXEC=section_start.sh
        ;;
    'table')
        OUTPUT='TableClassify'
        EXEC=table_start.sh
        ;;
    *)
        usage
esac

if [[ "$3" == "-o" ]]
  then 
    OUTPUT=$4
fi

echo output_path=./data/$OUTPUT/ > $BASE/conf/classify/path.properties
echo log_path=./logs/$OUTPUT/ >> $BASE/conf/classify/path.properties
echo "The data output path will be 'data/$OUTPUT'"
echo "The log output path will be 'log/$OUTPUT'"

cd $BASE/modules/classify
chmod +x $EXEC
./$EXEC

exit 1
return 1

