#!/bin/sh

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
# echo $SCRIPTPATH

BASE=$SCRIPTPATH/..
PWD=`pwd`

# import result to mongo
echo 'Importing result to mongo ...'
cd $BASE/modules/classify
chmod +x import.sh
sh import.sh $*
cd $PWD
echo 'Importing done.'
exit 1
