#!/bin/sh

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
# echo $SCRIPTPATH

BASE=$SCRIPTPATH/..
PWD=`pwd`

# convert Chinese folder name from GBK to UTF-8
# ONLY FOR Linux!!!
echo 'Convert folder name encoding ...'
convmv -f ISO-8859-1 -t UTF-8 -r --notest $1
echo 'Converting complete.'
echo 'Delete temperory files and directories, such as .files folder ...'
#find $1 -name .files | xargs rm -fr -
echo 'Done.'
