#!/bin/sh

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
# echo $SCRIPTPATH

BASE=$SCRIPTPATH/..
PWD=`pwd`

# Document Parsing
echo 'Document parsing ...'
cd $BASE/modules/docparse
ant run -Dcmd="$*"
cd $PWD
echo 'Document parsing result has been stored in MongoDB.'
