#!/bin/sh

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
# echo $SCRIPTPATH

BASE=$SCRIPTPATH/..
PWD=`pwd`

echo 'Fix file path for special characters ...'
cd $BASE/modules/word2html
ant run -Dcmd="$*"
cd $PWD
echo 'File path fixing done.'
