#!/bin/sh

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
# echo $SCRIPTPATH

BASE=$SCRIPTPATH/..
PWD=`pwd`

# Mobile Ontology
echo 'CMCC core ontology generating ...'
cd $BASE/modules/ontology
#ant tab
ant run -Dcmd="$*"
#ant csv
cd $PWD
echo 'Core ontology generated into owl & csv files.'
