#!/bin/sh

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
# echo $SCRIPTPATH

BASE=$SCRIPTPATH/..
PWD=`pwd`

# Mobile Ontology to CSV
echo 'CMCC core ontology CSV generating ...'
cd $BASE/modules/ontology
ant csv -Dcmd="$*"
cd $PWD
echo 'Core ontology generated into CSV files.'
