#!/bin/sh

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
# echo $SCRIPTPATH

BASE=$SCRIPTPATH/..
PWD=`pwd`

# Mobile Ontology to HTML
echo 'Ontology to HTML ...'
cd $BASE/modules/ontology
ant owl2html -Dcmd="$*"
cd $PWD
13 echo 'Core ontology generated into HTML files.'
