#!/bin/sh

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
# echo $SCRIPTPATH

BASE=$SCRIPTPATH/..
PWD=`pwd`

# QA Extraction
echo "QA pairs extracting ..."
cd $BASE/modules/qa
ant -Dcmd="$*"
cd $PWD
echo "QA pairs has been stored in files."
