#!/bin/sh
 
# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
# echo $SCRIPTPATH

BASE=$SCRIPTPATH/..
PWD=`pwd`

# split word by CMCC service
echo 'Splitting word ...'
cd $BASE/modules/splitword
ant run -Dcmd="$*"
cd $PWD
echo 'Splitting word completes, results has been stored in MongoDB.'
