#!/bin/sh

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
# echo $SCRIPTPATH

BASE=$SCRIPTPATH/..
PWD=`pwd`

# preparation for similar property merging
echo 'Running automatic similar property merging ...'
cd $BASE/modules/spm
ant run -Dcmd="$*"
cd $PWD
echo 'Similar property merging result has been generated in data/spm directory.'
