#!/bin/sh

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
# echo $SCRIPTPATH

BASE=$SCRIPTPATH/..
PWD=`pwd`

# Mobile Ontology
echo 'Table data writing back ...'
cd $BASE/modules/table
ant mantab -Dcmd="$*"
cd $PWD
echo 'Writing back completes.'
